apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  template:
    spec:
      containers:
        - name: backend
          image: ghcr.io/nadzzdan/3tier-backend:sha-bdfe7339a94cbabae811b07f69ff928edee6a5b7
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: ghcr.io/nadzzdan/3tier-frontend:sha-bdfe7339a94cbabae811b07f69ff928edee6a5b7
