apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: webapp-ingress-prod
  namespace: three-tier
spec:
  rules:
  - host: frontend.three-tier.local
    http:
      paths:
      - backend:
          service:
            name: frontend-prod
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: backend.three-tier.local
    http:
      paths:
      - backend:
          service:
            name: backend-prod
            port:
              number: 8000
        path: /
        pathType: Prefix
