name: CI - Build & Push to GHCR

on:
  push:
    tags:
      - "v*.*.*"   # Only runs when a version tag is pushed (e.g., v0.1.0)

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, backend]   # Build both frontend and backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag version
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}   # ./frontend or ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ env.TAG }}
