apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: three-tier
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: ghcr.io/owner/3tier-backend:sha-PLACEHOLDER
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: { name: backend-config }
          env:
            - name: MYSQL_PASSWORD
              valueFrom: { secretKeyRef: { name: db-secret, key: MYSQL_PASSWORD } }
          readinessProbe:
            httpGet: { path: /docs, port: 8000 }
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /docs, port: 8000 }
            initialDelaySeconds: 15
            periodSeconds: 20
