apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: three-tier
resources:
  - namespace.yaml
  - configmap-backend.yaml
  - secret-db.yaml
  - mysql-statefulset.yaml
  - mysql-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
