name: CI - Build & Push to GHCR

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write  # needed to push to GHCR
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_BACKEND: ghcr.io/${{ github.repository_owner }}/3tier-backend
  IMAGE_FRONTEND: ghcr.io/${{ github.repository_owner }}/3tier-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [ backend, frontend ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define image name
        id: img
        run: |
          if [ "${{ matrix.component }}" = "backend" ]; then
            echo "IMAGE=${{ env.IMAGE_BACKEND }}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE=${{ env.IMAGE_FRONTEND }}" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          push: true
          tags: |
            ${{ steps.img.outputs.IMAGE }}:sha-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
